### ISSUE TITLE
[Bug] seed.py 랜덤 에러

### ISSUE THREAD

**Issue by njs03332** [ssm0318/WhoamI-Today-backend#163]
shell에서 seed하면 가끔 아래와 같은 에러가 나네요..!
```shell
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/whoami/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "unique_response_request"
DETAIL:  Key (requester_id, requestee_id, question_id)=(10, 9, 1) already exists.
```

요 부분이 문제인 것 같아요 (랜덤하게 유저를 넣음)
```python
    # Seed Response Request
    for _ in range(n):
        question = random.choice(questions)
        requester = random.choice(users)
        requestee = random.choice(users.exclude(id=requester.id))
        ResponseRequest.objects.create(requester=requester, requestee=requestee, question=question,
                                       message=faker.catch_phrase())
    logging.info(
        f"{ResponseRequest.objects.count()} ResponseRequest(s) created!") if DEBUG else None
```

**Comment by njs03332** [comment]
이런 에러가 날 때도 있네용
```shell
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/user/Documents/git/WhoAmI-Today-backend/adoorback/adoorback/test/seed.py", line 186, in set_seed
    comment = random.choice(comments)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/whoami/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
  File "/opt/homebrew/Caskroom/miniforge/base/envs/whoami/lib/python3.9/site-packages/django/db/models/query.py", line 300, in __getitem__
    return self._result_cache[k]
IndexError: list index out of range
```
