### ISSUE TITLE
[Bug] POST /api/user/friend-requests/ 500 error(`psycopg2.errors.UndefinedTable: relation "notification_notification_actors" does not exist`)

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#179]
**내용**
POST /api/user/friend-requests/ 500 error [postman](https://diivers.postman.co/workspace/WhoAmI~c2317c3a-2ab1-458e-96b5-01f8ca6b983e/request/6673035-c18e22a2-6961-4519-80a5-4441e0196ef9)
<img width="787" alt="스크린샷 2024-03-23 오후 5 34 36" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/ca6d6cfc-b7e7-4871-8c0f-17a0225c722d">

```
Internal Server Error: /api/user/friend-requests/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "notification_notification_actors" does not exist
LINE 1: INSERT INTO "notification_notification_actors" ("notificatio...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/opt/anaconda3/envs/diivers/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/user/Dev/WhoAmI-Today-backend/adoorback/account/views.py", line 655, in perform_create
    serializer.save(accepted=None)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/safedelete/models.py", line 129, in save
    super(SafeDeleteModel, self).save(**kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/user/Dev/WhoAmI-Today-backend/adoorback/account/models.py", line 351, in create_friend_noti
    noti.actors.add(requester)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 1137, in add
    self._add_items(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 1403, in _add_items
    self.through._default_manager.using(db).bulk_create(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 803, in bulk_create
    returned_columns = self._batched_insert(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 1839, in _batched_insert
    self._insert(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "notification_notification_actors" does not exist
LINE 1: INSERT INTO "notification_notification_actors" ("notificatio...
```

**이미지**

**테스트 환경**
데스크탑 / 모바일 / 브라우저 등

**Comment by GooJinSun** [comment]
비슷한 에러인 것 같아 추가합니다!
POST `/api/qna/questions/response-request/`

```
HTTP POST /api/qna/questions/response-request/ 500 [0.53, 127.0.0.1:53057]
Internal Server Error: /api/qna/questions/response-request/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "notification_notification_actors" does not exist
LINE 1: INSERT INTO "notification_notification_actors" ("notificatio...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/opt/anaconda3/envs/diivers/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/user/Dev/WhoAmI-Today-backend/adoorback/qna/views.py", line 217, in perform_create
    serializer.save()
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/safedelete/models.py", line 129, in save
    super(SafeDeleteModel, self).save(**kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/user/Dev/WhoAmI-Today-backend/adoorback/qna/models.py", line 190, in create_response_request_noti
    Notification.objects.create_or_update_notification(user=requestee, actor=requester,
  File "/Users/user/Dev/WhoAmI-Today-backend/adoorback/notification/models.py", line 81, in create_or_update_notification
    noti.actors.add(actor)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 1137, in add
    self._add_items(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 1403, in _add_items
    self.through._default_manager.using(db).bulk_create(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 803, in bulk_create
    returned_columns = self._batched_insert(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 1839, in _batched_insert
    self._insert(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "notification_notification_actors" does not exist
LINE 1: INSERT INTO "notification_notification_actors" ("notificatio...
```

**Comment by GooJinSun** [comment]
https://github.com/GooJinSun/WhoAmI-Today-backend/pull/156

로컬에서 위 브랜치 테스트 이후 발생하는 걸로 추정. 디비 날리고 다시 확인해보겠습니다~

**Comment by ssm0318** [comment]
@GooJinSun 요거 해결된거죠?

**Comment by njs03332** [comment]
추가 에러.. 백엔드 seed를 하지 않고 signup POST 요청을 보내는 경우 아래 에러가 남

```
{
    "detail": "User not found",
    "code": "user_not_found"
}
```

**Comment by njs03332** [comment]
superuser가 없을 때 생기는 에러인 것으로 확인됩니다! 
첫 유저로 superuser를 생성한 후에 다른 유저들을 생성하는 경우 위의 API 모두 정상동작합니다.
@GooJinSun 시간되실 때 확인해주시고 잘 되면 close 부탁드려요 !! :)

**Comment by GooJinSun** [comment]
seed로 슈퍼유저 생성 후에 시도해보니 정상 응답 확인해서 이슈 클로즈합니다.
확인 감사합니다;)
![image](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/54881e98-cbd4-4b35-9bb5-5799172045c7)
