### ISSUE TITLE
[Bug] 회원가입 API 서버 에러(`IntegrityError`)

### ISSUE THREAD

**Issue by GooJinSun** [ssm0318/WhoamI-Today-backend#60]
**내용**
회원가입 API(`/api/user/signup/`)
### 요청 파라미터
```
{
email: "oneroof@oneroof.com",
noti_on: true,
noti_time: "03:04",
password: "Oneroof1234!",
profileImage: File {name: 'data:image/jpeg;base64,/9j/4W+9RXhpZgAASUkqAAgAAAA…AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_cropped.jpg', lastModified: 1692064729766, lastModifiedDate: Tue Aug 15 2023 10:58:49 GMT+0900 (한국 표준시), webkitRelativePath: '', size: 3713610, …}
research_agreement: false,
username: "oneroof"
}
```
### 이미지
![image](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/adf39ac4-eca4-4efd-a322-78ee998a1fe8)

### bug log
```
Internal Server Error: /api/user/signup/
Traceback (most recent call last):
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "noti_on" of relation "account_user" violates not-null constraint
DETAIL:  Failing row contains (20, 2023-08-15 01:59:03.09897+00, 2023-08-15 01:59:03.099008+00, pbkdf2_sha256$260000$JVmA4f3MbNYlZSTdOtbSLD$w1EFw/pUCWHQNMMO7gdB..., null, f, oneroof, , , f, t, 2023-08-15 01:59:02.949011+00, oneroof@oneroof.com, null, #CC5008, null, null, f, null, , ko, null, f, null, null, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/Users/user/Dev/WhoAmI-Today-backend/adoorback/account/views.py", line 191, in create
    self.perform_create(serializer)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/user/Dev/WhoAmI-Today-backend/adoorback/account/serializers.py", line 45, in create
    user.save()
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/safedelete/models.py", line 129, in save
    super(SafeDeleteModel, self).save(**kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/anaconda3/envs/diivers/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "noti_on" of relation "account_user" violates not-null constraint
DETAIL:  Failing row contains (20, 2023-08-15 01:59:03.09897+00, 2023-08-15 01:59:03.099008+00, pbkdf2_sha256$260000$JVmA4f3MbNYlZSTdOtbSLD$w1EFw/pUCWHQNMMO7gdB..., null, f, oneroof, , , f, t, 2023-08-15 01:59:02.949011+00, oneroof@oneroof.com, null, #CC5008, null, null, f, null, , ko, null, f, null, null, null, null, null).
```

**Comment by njs03332** [comment]
제가 푸시노티 on/off 설정 구현하면서 `noti_on` 필드를 만들었는데요..!
회원가입시에 유저가 알림을 on 설정하는 로직이 따로 없다면 디폴트로 `noti_on: False`로 해서 API 요청을 날리고,
유저가 알림을 on 설정하는 과정이 있다면 유저가 알림 받도록 설정한 경우 `True`, 아닌 경우 `False`로 설정해서 날려주실 수 있을까요~?
푸시노티 on/off 관련해서는 디바이스별로 가능하도록 수정이 될 예정이라 이 부분도 바뀔 수 있긴 한데, 현재로서는 이렇게 설정해야 동작하는 상황입니다..! ㅠㅠ 
혹시 제가 잘못 생각한 부분이 있다면.. 말씀해주세요 ! :)
<img width="999" alt="스크린샷 2023-08-15 오전 11 33 10" src="https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37107740/4ae5f141-a2d2-4b48-8874-912385022638">

**Comment by GooJinSun** [comment]
DB를 날리고 다시 시도해보니 정상동작 확인해서 이슈 클로즈합니다
확인 감사합니다!

![image](https://github.com/GooJinSun/WhoAmI-Today-backend/assets/37523788/be1b32f1-2289-42b2-be89-584efe0125f8)
